apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-g613
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-g613
    app.kubernetes.io/part-of: test-app-861
  name: pip-e2e-test-g613
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-g613
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-g613
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-861/pip-e2e-test-g613@sha256:9c7cd01d7c062b563a4b3046dd06e0135ffac06323df61e9ebe4582dc9199c17
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
