apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-vsxr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-vsxr
    app.kubernetes.io/part-of: test-app-861
  name: devfile-sample-python-basic-vsxr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-vsxr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-vsxr
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-861/devfile-sample-python-basic-vsxr@sha256:fa05f60ad5827cdecb5310252060a41196e3c80e4b8e5f883a72cb97c812b447
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
