apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-rzty
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-rzty
    app.kubernetes.io/part-of: test-app-861
  name: retrodep-rzty
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-rzty
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-rzty
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-861/retrodep-rzty@sha256:dfd38c84c91b3e99bfb9c20d91a7c1f7de7a5555b3c133c3113561b36d86380a
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
