apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-zvgk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-zvgk
    app.kubernetes.io/part-of: test-app-861
  name: maven-hello-world-zvgk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-zvgk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-zvgk
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-861/maven-hello-world-zvgk@sha256:ecbaf73e92f508c2003a77720e3049280a713e8cf8860785e233e688db08374a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
