apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-3jt8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-use-latest-parent-image-3jt8
    app.kubernetes.io/part-of: test-app-861
  name: e2e-tests-use-latest-parent-image-3jt8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-3jt8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-3jt8
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-861/e2e-tests-use-latest-parent-image-3jt8@sha256:c9b299d9ed9e48d14caa47e966f3781e5ae95926d55387701ccc5404f5aa75cc
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
